"""Add is_playing field

Revision ID: 5290655ea592
Revises: b6cc91666717
Create Date: 2016-08-31 12:43:37.592948

"""

# revision identifiers, used by Alembic.
revision = '5290655ea592'
down_revision = 'b6cc91666717'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('play_lists', sa.Column('is_playing', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('play_lists', 'is_playing')
    ### end Alembic commands ###
