"""create play list table

Revision ID: a8d0e040ed40
Revises: 
Create Date: 2016-07-26 23:07:51.379218

"""

# revision identifiers, used by Alembic.
revision = 'a8d0e040ed40'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('play_lists')
    ### end Alembic commands ###
